### ISSUE TITLE
Please add a new parameter BtchBookg

### ISSUE THREAD

**Issue by MicrotronX** [aspettl/delphi-sepa-xml#2]
We need the "**BtchBookg**" parameter in XML output. We have changed source on our side, please add it to your code:

TCreditTransferPaymentInformation = class
private
...
fBtchBookg:string; // set it to "false" in onCreate
public
...
property BtchBookg: String read fBtchBookg write fBtchBookg;
...

and write it to XML right after "PmtMtd" 

procedure TCreditTransferPaymentInformation.SaveToStream(const stream: TStream; const schema: String);
begin
  SEPAWriteLine(stream, '<PmtInf>');
  SEPAWriteLine(stream, '<PmtInfId>'+SEPACleanString(PmtInfId)+'</PmtInfId>');
  SEPAWriteLine(stream, '<PmtMtd>'+SEPACleanString(PmtMtd)+'</PmtMtd>');

  //>>
  SEPAWriteLine(stream, '<BtchBookg>'+SEPACleanString(fBtchBookg)+'</BtchBookg>');

**Comment by aspettl** [comment]
Thanks, it would be great if you can prepare a pull request!

Please note:
* fBtchBookg should be a boolean
* direct debit should support batch booking as well
* unit tests should be adjusted/extended accordingly

This makes it a lot easier for me to accept changes quickly.

If you want to contribute directly: note that I just switched to a dual-license of Apache 2.0 or GPLv2-or-later.

**Comment by MicrotronX** [comment]
I'm not allowed to create a pull request.

**Comment by aspettl** [comment]
Fixed by https://github.com/aspettl/delphi-sepa-xml/pull/4
